### PR TITLE
2020-12-09 join update

### PR DESCRIPTION
**Pull request by samuelstevens9**
Round #6 Join UPDATE -- Due 12/11

Change page title to to “Join and Participate”

Add two dropdown pages:

                Sponsoring Members – 

		Supporters – 

		Communities – NO CHANGE

		Ambassadors – NO CHANGE

### CODE REVIEW

**Comment by frickealissa** [comment]
#39 

@samuelstevens9 

on Join and Participate:
- Make "The" lowercase "the" in title

- Can we change the text to not be left aligned?

- If I create jpg graphic images for each "SPONSORING MEMBERS" "COMMUNITIES" SUPPORTERS" "AMBASSADORS", could we use these images as linked buttons replacing the words?

**Comment by samuelstevens9** [comment]
> * Can we change the text to not be left aligned?

@frickealissa Which text and which alignment would you like?

image

**Comment by frickealissa** [comment]
> > * Can we change the text to not be left aligned?
> 
> @frickealissa Which text and which alignment would you like?
> 
> image

"The industry.." and the paragraph below it. I guess it's not as much just left aligned as it is the width of the text not expanding to the full page. I think we talked about before that it may be an issue with the template that is hard to change.

**Comment by frickealissa** [comment]
> > * Can we change the text to not be left aligned?
> 
> @frickealissa Which text and which alignment would you like?
> 

@samuelstevens9 I am emailing the graphics for the SUPPORTERS, SPONSORING MEMBERS, etc. buttons

**Pull request merged**
